CREATE DATABASE IF NOT EXISTS midb;
CREATE TABLE IF NOT EXISTS DATOS (Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Nombres VARCHAR(30) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,Email VARCHAR(30) NOT NULL,Lenguaje VARCHAR(30) NOT NULL, Hobbies VARCHAR(300) NOT NULL);